# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POST_ROOT_PASSWORD}
      POSTGRES_USER: ${POST_USER}
      POSTGRES_DB: ${POST_DB}
      POSTGRES_PORT: ${POST_PORT}:${POST_PORT}
      expose: POST_PORT
      ipaddress: "192.168.0.25"
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
    networks:
        - my-networks

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
    networks:
      - my-networks
  
networks:
  my-networks:
    driver: bridge 